---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-release-pipeline}

inputs:
- name: boshrelease
- name: boshrelease-ci
- name: dingo-postgresql95
  path: images/dingo-postgresql95

outputs:
- name: boshrelease-images-updated

params:
  aws_access_key_id:
  aws_secret_access_key:

run:
  path: boshrelease-ci/ci/tasks/bump-image-layers.sh
