---
groups:
- name: images
  jobs: [bump-layers, bosh-rc, testflight]

jobs:
- name: bump-layers
  public: true
  serial_groups: [boshrelease]
  plan:
  - aggregate:
    - {get: dingo-postgresql95, trigger: true, params: {save: true}}
    - {get: boshrelease}
    - {get: boshrelease-ci}
  - task: bump-image-blob
    file: boshrelease-ci/ci/tasks/bump-image-layers.yml
    params:
      aws_access_key_id: {{cfcommunity-aws-access}}
      aws_secret_access_key: {{cfcommunity-aws-secret}}
  - put: boshrelease
    params: {repository: boshrelease-images-updated, rebase: true}

- name: bosh-rc
  public: true
  plan:
  - aggregate:
    - {get: boshrelease-ci}
    - {get: boshrelease, passed: [bump-layers], trigger: true}
    # - {get: version, passed: [bump-layers], trigger: true}
    - {put: version, params: {pre: rc}}
  - task: create-candidate-release
    file: boshrelease-ci/ci/tasks/create-candidate-release.yml
    params:
      aws_access_key_id: {{dingotiles-aws-access}}
      aws_secret_access_key: {{dingotiles-aws-secret}}
  - put: candidate-release
    params: {file: candidate-release/dingo-postgresql-*.tgz}

- name: testflight
  public: true
  serial: true
  plan:
  - aggregate:
    - {get: boshrelease-ci}
    - {get: boshrelease, passed: [bosh-rc]}
    - {get: candidate-release, passed: [bosh-rc], trigger: true}
    - {get: dingo-postgresql-release}
    - {get: version, passed: [bosh-rc]}
    - {get: dingo-postgresql-release-manifests}
  - task: create-lite-manifest
    file: boshrelease-ci/ci/tasks/create-manifest.yml
    params:
      deployment_name: dingo-postgresql-testflight
      bosh_target: {{bosh-lite-testflight-target}}
      bosh_username: {{bosh-lite-username}}
      bosh_password: {{bosh-lite-password}}
      aws_access_key: {{dingotiles-aws-access}}
      aws_secret_key: {{dingotiles-aws-secret}}
      backups_bucket: {{backups-testflight-backups-bucket}}
      clusterdata_bucket: {{backups-testflight-clusterdata-bucket}}
      region: {{backups-testflight-s3-region}}
  - put: lite-deployment-testflight
    params:
      manifest: manifest/manifest.yml
      stemcells: [lite-stemcell/*.tgz]
      releases:
        - candidate-release/*.tgz
        - etcd/*.tgz
        - simple-remote-syslog/*.tgz
  - put: sanity-test
    resource: lite-errand-testflight
    params:
      manifest: manifest/manifest.yml
      errand: sanity-test
    on_failure:
      task: show-broker-logs
      file: boshrelease-ci/ci/tasks/show-broker-logs.yml
      params:
        bosh_target: {{bosh-lite-testflight-target}}
        bosh_username: {{bosh-lite-username}}
        bosh_password: {{bosh-lite-password}}

resources:
- name: boshrelease
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-postgresql-image-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: boshrelease-ci
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-postgresql-image-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: dingo-postgresql95
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/dingo-postgresql95

- name: dingo-postgresql-release
  type: github-release
  source:
    user: dingotiles
    repository: dingo-postgresql-release
    access_token: {{github-release-access-token}}

- name: dingo-postgresql-release-manifests
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-postgresql-release.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.10.2
    uri: git@github.com:dingotiles/dingo-postgresql-image-boshrelease.git
    branch: version
    file: version
    private_key: {{github-private-key}}

- name: candidate-release
  type: s3
  source:
    bucket: dingo-postgresql-image-release-candidates
    regexp: dingo-postgresql-image-(.*).tgz
    access_key_id: {{dingotiles-aws-access}}
    secret_access_key: {{dingotiles-aws-secret}}
    region_name: {{dingotiles-aws-region}}

- name: lite-deployment-testflight
  type: bosh-deployment
  source: &lite-testflight-defaults
    target: {{bosh-lite-testflight-target}}
    username: {{bosh-lite-username}}
    password: {{bosh-lite-password}}
    deployment: dingo-postgresql-testflight

- name: lite-errand-testflight
  type: bosh-errand
  source: *lite-testflight-defaults
